-- Finding the total customers by country
SELECT
	country,
	COUNT (customer_key) AS [total_customers]
FROM dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Finding the total customers by gender
SELECT
	gender,
	COUNT (customer_key) AS [total_customers]
FROM dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Finding the total products by category
SELECT
	category,
	COUNT (product_key) AS [total_products]
FROM dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average cost in each product category
SELECT
	category,
	AVG (cost) AS [avg_cost]
FROM dim_products
GROUP BY category
ORDER BY avg_cost DESC

-- What is the total revenue generated by each product category
SELECT
	p.category,
	SUM (f.sales_amount) AS [total_revenue]
FROM fact_sales AS [f]
LEFT JOIN dim_products AS [p]
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- What is the total revenue generated by each customer
SELECT
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM (f.sales_amount) AS [total_revenue]
FROM fact_sales AS [f]
LEFT JOIN dim_customers AS [c]
ON c.customer_key = f.customer_key
GROUP BY
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries
SELECT
	c.country,
	SUM (f.quantity) AS [total_items_sold]
FROM fact_sales AS [f]
LEFT JOIN dim_customers AS [c]
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_items_sold DESC